### ISSUE TITLE
ext_tables_static+adt.sql not loaded automatically

### ISSUE THREAD

**Issue by githubrsys** [bednee/cooluri#20]
It seems that ext_tables_static+adt.sql get not autoloaded. I cannot see the cache tables after Installation.

**Comment by bednee** [comment]
Yesterday I installed CoolUri on fresh TYPO3 7 and it was flawless. I install CoolUri regulary on websites I create and I have never had any problem.

**Comment by githubrsys** [comment]
The point is that here a cooluri was installed, but not active. The tables were deleted once.  By reinstalling the extension the tables were not created nor did the installtool 'compare' function complain about these and did not create them also. 

It was only possible to manually create them.

Cheers
