### ISSUE TITLE
Support for TYPO3 4.5

### ISSUE THREAD

**Issue by TomOne** [bednee/cooluri#22]
Since the latest few commits on master, CoolURI no longer works with TYPO3 4.5. Is that intended? According to the description on [TER](https://typo3.org/extensions/repository/view/cooluri) it should support TYPO3 4.5 too.

**Comment by bednee** [comment]
I have tested it with 4.5 and didn't spot any errors. Can you be more specific a give me the errors you are getting? 

11. března 2015 9:14:17 SEČ, TomOne <notifications@github.com> napsal:
>Since the latest few commits on master, CoolURI no longer works with
>TYPO3 4.5. Is that intended? According to the description on
>[TER](https://typo3.org/extensions/repository/view/cooluri) it should
>support TYPO3 4.5 too.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bednee/cooluri/issues/22

-- 
Odesláno z mého telefonu s Androidem pomocí pošty K-9 Mail. Omluvte prosím moji stručnost.

**Comment by TomOne** [comment]
I get this error:

> Fatal error: Class 'TYPO3\CMS\Core\Utility\GeneralUtility' not found in /var/www/vhosts/mysite.com/httpdocs/typo3conf/ext/cooluri/class.tx_cooluri.php on line 77

**Comment by bednee** [comment]
class_alias function is used to register this class in case of 4.5. This 
function is available since PHP 5.3. Is it possible that your PHP 
version is lower?

This is in class.tx_cooluri.php

if (!class_exists('\TYPO3\CMS\Core\Utility\GeneralUtility')) {
     class_alias('t3lib_div','\TYPO3\CMS\Core\Utility\GeneralUtility');
}

I've just tested CoolUri on my local 4.5 installation and it's working fine.

H

Dne 11. 3. 2015 v 9:29 TomOne napsal(a):

**Comment by jaapen** [comment]
I have the same Problem with PHP Version 5.3.3-7.

```
 PHP Fatal error:  Class 'TYPO3\\CMS\\Core\\Utility\\GeneralUtility' not found in /var/www/my-site/typo3conf/ext/cooluri/class.tx_cooluri.php on line 79
```

**Comment by bednee** [comment]
Hmm, I have no idea how's possible that it works somewhere and somewhere not. Anyone able to find solution?

**Comment by bednee** [comment]
CoolUri has been refactored and supports only 6+ TYPO3 now.
