### ISSUE TITLE
Core update leads to "page not found"

### ISSUE THREAD

**Issue by DenisMir** [bednee/cooluri#23]
After an core patch update from TYPO3 6.2.9 to 6.2.11 I'm getting only a "page not found". If I disable cooluri everything works as expected.

**Comment by DenisMir** [comment]
I'm now able to reproduce the error. The database analyzer of the install tool is suggesting the following: 

```sql
ALTER TABLE link_cache RENAME zzz_deleted_link_cache; 
Records in table: 10

ALTER TABLE link_oldlinks RENAME zzz_deleted_link_oldlinks;
```

This leads to the mentioned error. I don't know if this is fixable. But it would be nice to do so.

I have manually added the tables again and everything works as expected.

**Comment by patkar** [comment]
The table definitions are in `ext_tables_static+adt.sql` and thus not detected by the compare tool. I think they should be moved to the `ext_tables.sql` files

See #27

**Comment by bednee** [comment]
Check the latest source here on GitHub.
