### ISSUE TITLE
Strict Standards: Accessing static property Link_Translate::$uri as non static in...

### ISSUE THREAD

**Issue by lochmueller** [bednee/cooluri#24]
... typo3conf/ext/cooluri/cooluri/link.Translate.php on line 403.
The Variable $uri is used sometimes as "static" with self and sometimes "non static" in object context.

It would be nice if this were clean, to avoid PHP "Strict Standards" errors...

Regards,
Tim

**Comment by bednee** [comment]
Should be fixed by now.
