### ISSUE TITLE
Move table definitions for link_cache and link_oldlinks to ext_tables.sql?

### ISSUE THREAD

**Issue by patkar** [bednee/cooluri#27]
It would be better to put the table definitions of the `link_cache` and `link_oldlinks` table to the `ext_tables.sql` file so they get detected by the compare tool and not accidentally deleted.

**Comment by bednee** [comment]
Already done

**Comment by patkar** [comment]
Oh, I see in #11. But was not clearly to see, if a PR does more than the thing described. But then, can we get a release with all the fixes?
