### ISSUE TITLE
fails to work on 6.2.14 

### ISSUE THREAD

**Issue by githubrsys** [bednee/cooluri#29]
Commit c5408a9cb4e1ec043ac9dba9bb8c9edb71afd37a produces following errors in log:

````
Core: Error handler (FE): PHP Warning: array_reverse() expects parameter 1 to be array, null given in /var/www/web7/html/devel/typo3conf/ext/cooluri/Classes/Core/Translate.php line 616

Core: Error handler (FE): PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'tx_cooluri' not found in /var/www/web7/html/devel/typo3conf/ext/cooluri/Classes/Core/Functions.php line 334
````

Downgrade to 93ab12e25f4178bd781a4d8244e6de8e24a941a0 works

php 5.5.28
typo3 6.2.14

**Comment by bednee** [comment]
Have a look <pagepath> in CoolUriConf.xml_default, the userFunc there has to look like this now:

**Comment by bednee** [comment]
<userfunc>Bednarik\Cooluri\Integration\Cooluri->getPageTitle</userfunc>

**Comment by fhofer** [comment]
I don't get it!
Uninstalled v1.1.1 completely and reinstalled it in typo3 6.2. Got above error.
CoolUriConf.xml_default is correct but CoolUriConf.xml in typo3conf wasn't...?!?

**Comment by bednee** [comment]
CoolUriConf.xml is yours, you need to change it manually. _default is shipped with the ext for reference and quick start.

**Comment by fhofer** [comment]
Thank you for the quick response!
I would bet CoolUriConf.xml wasn't there anymore after uninstall and then recreated again (wrong)...?!?
