### ISSUE TITLE
Typo3 7 LTS support

### ISSUE THREAD

**Issue by DenisMir** [bednee/cooluri#35]
When trying to enable cooluri on Typo3 7 LTS I'm getting a 404 error when trying to access the pages with a correct cooluri link. The link is also available in the cooluri cache.

**Comment by bednee** [comment]
Is it CoolUri's 404 or Apache server 404?

**Comment by DenisMir** [comment]
I'm having a look. It seems to be coming from the Apache. (I think it could be the htaccess file...)

**Comment by DenisMir** [comment]
Ok the htaccess file got dropped. I'm sorry for the issue.
