### ISSUE TITLE
TYPO3 7.6 Uncaught TYPO3 Exception

### ISSUE THREAD

**Issue by r4fx** [bednee/cooluri#38]
Cooluri doesn't work with TYPO3 7.6 LTS,
throws an error:

`
#1: PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'tx_cooluri' not found in /home/public_html/project/typo3conf/ext/cooluri/Classes/Core/Functions.php line 335
`

**Comment by bednee** [comment]
Read the upgrade notes for 1.1.1. You need to change pagepath/userfunc to Bednarik/Cooluri... (it's in the default XML).
