### ISSUE TITLE
mysql_error() undefined when using php 7

### ISSUE THREAD

**Issue by UncleWaldo** [bednee/cooluri#52]
Running TYPO3 7.6.9 with cooluri.
Everything works fine with php 5.6.5, however when changing to php 7 I receive 
`Call to undefined function Bednarik\Cooluri\Core\mysql_error()`

**Comment by bednee** [comment]
I believe it's already fixed, see commit https://github.com/bednee/cooluri/commit/fdbd7efa57664474e7691eba9f5308796cd28b08
