### ISSUE TITLE
Add Git tags

### ISSUE THREAD

**Issue by mbrodala** [bednee/cooluri#6]
Please add Git tags for every released version. Currently `1.0.37` could be added for d964623.

**Comment by davidspiess** [comment]
In https://github.com/bednee/cooluri/releases/tag/1.0.39 the version number is still at 1.0.36.
This should be fixed by releasing a 1.0.40.

**Comment by bednee** [comment]
The tags are now mess. I will make it right with next release. I have just put 1.0.39 to TER.
