### ISSUE TITLE
TYPO3 8.6 compatibility

### ISSUE THREAD

**Issue by pitchart** [bednee/cooluri#64]
As for issue #53, cooluri is not ready for TYPO3 CMS 8.6.

I'm migrating our current TYPO3 7.6 installation to the 8.6 because LTS is coming, and we will have to face this issue.
Do you have any guide lines to start implementing it ?

Thanks

**Comment by bednee** [comment]
I've just commited fix that should make CoolUri compatible - https://github.com/bednee/cooluri/commit/15f2b7f15126bdcb82d793efa27b0162fb58578c

Can you give it a try?

**Comment by Hobokens** [comment]
The first impression ist great (TYPO3 8.7. on a local system): no problems at all. Thanks a lot for the very helpful extension.
