### ISSUE TITLE
Wrong localized path issue

### ISSUE THREAD

**Issue by DenisMir** [bednee/cooluri#7]
I'm using the latest version of Typo3 6.2 LTS and I got a problem with the localized paths in CoolUri. 

Language Setup: 

* English default language
* German second language (additional language)

Here is the root typoscript template: 

```
# multi language setup
config.linkVars = L
config.uniqueLinkVars = 1
config.sys_language_uid = 0
config.language = en
config.locale_all = en_US.UTF8
config.htmlTag_langKey = en

[globalVar = GP:L = 1]
config.sys_language_uid = 1
config.language = de
config.locale_all = de_DE.UTF8
config.htmlTag_langKey = de
[global]
```

Here is the relevant part of the cooluri config (the other stuff is untouched): 

```xml
  <valuemaps>
    <valuemap>
      <parameter>L</parameter>
      <value key="">0</value>
      <value key="de">1</value>
    </valuemap>
  </valuemaps>
```

And here is the simplified page setup: 

One Page with the page title _Imprint_ and the german translation _Impressum_

And here is the error: 

* _/imprint_ - shows me the correct english content and the language menu shows me _/imprint_ for english and _/de/impressum_ for german
* _/de/impressum_ - shows me the correct german content and the language menu shows me _/de/impressum_ for german **but it shows me _/impressum_ for english**
* _/impressum_ - shows me the english content

I don't get the reason why the language menu renders these wrong paths.

And here are the cached links: 

* _impressum/_ - L=0&id=5
* _imprint/_ - id=5
* _de/impressum/_ - L=1&id=5

Have you got an explanation for the problem?

**Comment by bednee** [comment]
New version has just been uploaded to TER.
