### ISSUE TITLE
1.1.4 regression: pages.is_siteroot must be set for each domain

### ISSUE THREAD

**Issue by jpmschuler** [bednee/cooluri#71]
Since 1.1.4 my multidomain URL paths aren't generated from the root of the current domain anymore but from TYPO3 root. 

Every domain has it's own tree but starts about 5 levels deep from the TYPO3 root. The template record of each domain is set to "root" so the resulting URLs were like https://mydomain.com/mysub/mypage

Since 1.1.4 the URLs are like https://mydomain.com/hosting-folder/site-category/site-subcategory/mysub/mypage - working, but conveying unwanted information.

I copied the default pagepath config from the config xml example (cleaning cache and cooluri tables) which doesn't fix the issue. Temporary hotfix might be to set "remove from middle of page path to all category folder parent pages", but nevertheless this seems a to be a bug perhaps creating additional problems elsewhere.

**Comment by conversion1** [comment]
Did you activate the "use as root page" behaviour?

**Comment by jpmschuler** [comment]
thx @conversion1. Setting page "use a root page" (pages.is_siteroot) for each domain solves the problem.

This is a new requirement, which wasn't necessary before. Changing issue title in order to document this behaviour for others.

(There was a big problem in 4LTS with configuration inheritance across domains IIRC, thus this option was deactivated in the installation I detected this years ago , doesn't seem to be the case anymore with 7LTS).
