### ISSUE TITLE
Multidomain with Multidomains

### ISSUE THREAD

**Issue by cooltypo** [bednee/cooluri#86]
I use Cooluri now for about 10 years. And I really love this cute extension!

Now I have a question about Coluri and Multidomain:

The following Configuartion:

Page 1(Begin of Website1)
            ->  Domain Object 1
            ->  Domain Object 2
   ->subpages

Page 2(Begin of Website2)
            ->  Domain Object 3
            ->  Domain Object 4
            ->  Domain Object 5
   ->subpages

Config:

####################################
####################################

config.absRefPrefix = /
config.simulateStaticDocuments = 0
config.tx_cooluri_enable = 1

(multidoamin is checked)

So CoolUri saves the Domain in the cache-table as 

 ( CACHED URI LOOKS LIKE: )

domain1@produkts/info

Cooluri always takes the first DOMAIN OBJECT for internal links.
What I want is  to take the domain which I am on with the Browser so what i need is relative links
If I turn off MultiDoman it works but you cannot have to pages with the same name like startseite on domain2 and domain 5

So what I found out is:
 If I change the return value in the File: Functions.php
in the function:     public static function prepareforOutput($path,$lConf) {....

      $path = substr(strrchr($path, "@"), 1);
      return $path;
}
I do get relative Paths although they are still stored in the cache table with the domain like: domain1@produkts/info
these relative paths are correctly displayed in the browser but if i click on them they fail if the domain name is domain2.
EXAMPLE:
CACHED URI: domain1@produkts/info 
URI  shown in the BROWSER if i come over domain2: domain2@produkts/info 

But this links lead to nothing cause of course in the cache it is still with : domain1@produkts/info

SO HOW AND WHERE CAN I CHANGE COOLURI so that also this now relative links on domain2 lead to the correct link?

In PrepareForRedirect? 

Many Thanks in Advance

Check multidomain, You can also get relative links by changing on line of code in Functions.php:
in the function prepareforOutput:

public static function prepareforOutput($path,$lConf) {
    // path is empty or equal to suffix/prefix
    // so there won't be any suffix or prefix
    // just empty URL (root)
      if (empty($path) ||
        (!empty($lConf->cache->prefix) && $path==$lConf->cache->prefix) ||
        (!empty($lConf->cache->suffix) && $path==$lConf->cache->suffix)
       ) {
      return $path;
    }
      if (!empty($lConf->removetrailingslash) && $lConf->removetrailingslash==1) {
          $temppath = self::removeSlash($path);
          $el = $lConf->removetrailingslash;
          if (empty($el['include']) || preg_match('~'.(String)$el['include'].'~',$temppath)) {
              $path = $temppath;
          }
      }
      if (self::excludeInclude($path,$lConf->urlprefix)) {
          $path = (string)$path;    // I CHANGED THIS(ommiting the prefix) AND NOW You get relative links 
      }

Issue not yet solved this is a beginning what is still missing is the creation of reltative links
in domain 2

**Comment by prdt3e** [comment]
I had a similar problem.
I had a multidomain instance which shared pages.
But I could solve that with mountpoints (typo3).
In Databse -> id=20&mp=40_25

Or do you want multiple domains for a multi-page?

**Comment by ryrun** [comment]
How is this multidomain working now? There is no option to turn this on anymore.Atleast, i've no option in the extension lists.  I'm on Typo3 v9, upgraded from an older Typo3 version.

**Comment by bednee** [comment]
The extension configuration was moved to Setup in TYPO3 9.
