### ISSUE TITLE
non code issue: Add extension to Packagist

### ISSUE THREAD

**Issue by jpmschuler** [bednee/cooluri#87]
Could you add a Packagist entry, this just takes a few minutes if using github. If configuring the github integration it's a "configure once, will update automatically" solution.

> GitHub Service Hook
> 
> Enabling the Packagist service hook ensures that your package will always be updated instantly when you push to GitHub.
> 
> To do so you can:
> 
> Go to your GitHub repository
> Click the "Settings" button
> Click "Integrations & services"
> Add a "Packagist" service, and configure it with your API token, plus your Packagist username
> Check the "Active" box and submit the form
> You can then hit the "Test Service" button to trigger it and check if Packagist removes the warning about the package not being auto-updated.`

https://insight.helhum.io/post/174851830180/improvements-to-composertypo3org adds that in extensions.typo3.org you should add the packagist link afterwards.

**Comment by bednee** [comment]
Done. Thanks for the instructions.
