### ISSUE TITLE
[BREAKING] Mark v1.2 as incompatible with 8LTS and or make compatible to both LTS

### ISSUE THREAD

**Issue by jpmschuler** [bednee/cooluri#97]
The composer json should be updated to 
```
  "require": {
    "typo3/cms-core": "^9.5",
```
 and the current version should be replaced/withdrawn as is, as the changes for 9LTS compatibility  (thx for all of them!) introduced are breaking, e.g.
- `\Doctrine\DBAL\FetchMode` not available in 8LTS (older DBAL use PDO FetchMode)
- `pages.l10n_parent` not existing in 8LTS (pages_language_overlay table used)

As 1.2 also merged all PHP 7.2 compatibility updates it would be wonderful to have 8LTS compatibility for the future, nevertheless it is a hardship.

I'm working on a PR to fix the above, but don't know when it is ready, until then all 8LTS composer installs would break with Exceptions in the frontend and need to resort to a fixed <1.2 cooluri version.

**Comment by bednee** [comment]
Fixed and released as 1.2.1

**Comment by bednee** [comment]
1.1.5 is pretty stable and can be used with 8. I don't plan to add any new features or fix any outstanding issues that would need porting to 8.
