### ISSUE TITLE
PHP Warning (TYPO3 8.7.29, cooluri 1.1.5)

### ISSUE THREAD

**Issue by Hobokens** [bednee/cooluri#98]
Day after day I get a hundred times the following error message

`Core: Error handler (FE): PHP Warning: Use of undefined constant self - assumed 'self' (this will throw an Error in a future version of PHP) in /html/typo3/typo3conf/ext/cooluri/Classes/Core/Functions.php line 121 `

Kind regards
Hobokens

**Comment by bednee** [comment]
That's odd as this was fixed in 1.1.5, see https://github.com/bednee/cooluri/commit/cbacf4c9930f0f0b33e9c69a333b8a0fd543fe5b

**Comment by Hobokens** [comment]
Strange, after clearing the cache again and again and resinstalling cooluri 1.1.5. again - the error ist again.
Thanks for your great extension !!!!!
